server:
  address: 0.0.0.0
  port: 8001
  compression:
    enabled: true
  http2:
    enabled: true

  ssl:
    enabled: true
    key-alias: santomcat
    key-store: classpath:ssl/server.p12
    key-store-type: PKCS12

    key-password: Zerkalo82
    key-store-password: Zerkalo82
    trust-store-password: changeit

  error:
    whitelabel:
      enabled: false

spring:
  rabbitmq:
    host: ${server.address}
    # https - 5672, http - 15672
    port: 5672
    username: guest
    password: guest
    ssl:
      enabled: true
      key-store: ${server.ssl.key-store}
      key-store-type: PKCS12
      key-store-password: ${server.ssl.key-password}
      trust-store-password: ${server.ssl.trust-store-password}
#      trust-store: /Library/Java/JavaVirtualMachines/jdk-11.0.10.jdk/Contents/Home/lib/security/cacerts
    virtual-host: /

