server:
  address: 0.0.0.0
  port: 8001
  compression:
    enabled: true
  http2:
    enabled: true

  ssl:
    enabled: true
    key-alias: santomcat
    key-store: classpath:ssl/server.p12
    key-store-type: PKCS12

    key-password: Zerkalo82
    key-store-password: Zerkalo82
    trust-store-password: changeit

  error:
    whitelabel:
      enabled: false

spring:
  rabbitmq:
    host: ${server.address}
    # https - 5672, http - 15672
    port: 5672
    username: admin
    password: Zerkalo82
    ssl:
      enabled: true
      key-store: ${server.ssl.key-store}
      key-store-type: PKCS12
      key-store-password: ${server.ssl.key-password}
      trust-store-password: ${server.ssl.trust-store-password}
#      trust-store: /Library/Java/JavaVirtualMachines/jdk-11.0.10.jdk/Contents/Home/lib/security/cacerts
    virtual-host: /

  boot:
    admin:
      client:
        enabled: true
#        урл админки (из контейнера торчит 5555, но nginx перенаправляет на 8000)!!!
        url: https://solnce52004.ga:5555
        instance:
#        урл клиента (из контейнера торчит 8001)
#          обязательный путь для отображения всех метрик и графиков
#          в соответствии с настройками маски в настройках ниже
          management-url: https://solnce52004.ga:8001/actuator
#          обязательный путь для получения метрик
          health-url: https://solnce52004.ga:8001/actuator/health
#          необязательное название клиента для отображения в админке
          name: "rabbitMQ producer"
#          обязательный путь к метрикам клиента
          service-path: /actuator
#          домашняя страница сервиса (данного клиента)
          service-url: https://solnce52004.ga:8001

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  config: "classpath:log4j2.properties"
  level:
    ROOT: INFO
    org:
      springframework.web: DEBUG
      hibernate: INFO